#!/bin/bash
# Script to add a group to Linux system
if [ $(id -u) -eq 0 ]; then
        read -p "Enter group : " group1
        read -p "Enter group2 : " group2
        read -p "Enter group3 : " group3
        egrep "^$group1,$group2,$group3" /etc/group >/dev/null
        if [ $? -eq 0 ]; then
                echo "$group exists!"
                exit 1
        else
                /usr/sbin/groupadd  $group1
                /usr/sbin/groupadd  $group2
                /usr/sbin/groupadd  $group3
                [ $? -eq 0 ] && echo "Groups have been added to system!" || echo "Failed to add a group!"
        fi
else
        echo "Only root may add a group to the system"
        exit 2
fi
